# Generated by Django 3.2 on 2023-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookies',
            field=models.JSONField(default=dict),
        ),
    ]
