# Generated by Django 3.2 on 2023-10-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_cookies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
